;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-force-normal-state
	evil-forward-char
	evil-next-line
	evil-previous-line
	helm-M-x
	hydra-multiple-cursors/ladicle/mc/insert-numbers-and-exit
	hydra-multiple-cursors/mc/edit-lines-and-exit
	hydra-multiple-cursors/mc/insert-letters-and-exit
	hydra-multiple-cursors/mc/mark-all-like-this-and-exit
	hydra-multiple-cursors/mc/mark-previous-like-this
	hydra-multiple-cursors/mc/skip-to-previous-like-this
	select-window-3
	))

(setq mc/cmds-to-run-once
      '(
	evil-search-next
	hydra-multiple-cursors/mc/insert-numbers-and-exit
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/nil
	iedit-switch-to-mc-mode
	))
