(deftheme solarized-dark
  "Created 2019-01-16.")

(custom-theme-set-variables
 'solarized-dark
 '(ansi-color-names-vector ["#073642" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#657b83"])
 '(compilation-message-face (quote default))
 '(cua-normal-cursor-color "#839496")
 '(cua-read-only-cursor-color "#859900")
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-overwrite-cursor-color "#b58900")
 '(pos-tip-foreground-color "#93a1a1")
 '(pos-tip-background-color "#073642"))

(custom-theme-set-faces
 'solarized-dark
 '(button ((t (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#839496" :inverse-video t))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36"))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline nil :underline "#073642" :foreground "#839496" :background "#002b36" :box (:line-width 2 :color "#002b36" :style unspecified)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#073642"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#b58900" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight normal))))
 '(match ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :weight bold))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#073642" :underline "#284b54" :foreground "#839496" :background "#073642" :box (:line-width 1 :color "#073642" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#073642" :underline "#284b54" :foreground "#586e75" :background "#002b36" :box (:line-width 1 :color "#002b36" :style unspecified)))))
 '(region ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#93a1a1"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#073642"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#284b54"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#2aa198" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#586e75" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground unspecified :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#dc322f" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(completions-annotations ((t (:foreground "#586e75"))))
 '(cua-global-mark ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(cua-rectangle ((((class color) (min-colors 89)) (:inherit region :background "#d33682" :foreground "#002b36"))))
 '(cua-rectangle-noselect ((((class color) (min-colors 89)) (:inherit region :background "#073642" :foreground "#586e75"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#268bd2"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#839496" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :underline t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#d33682" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36" :bold t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#073642"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#839496" :weight bold :slant normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#586e75" :slant normal))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant normal))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:inherit error :weight bold))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#2aa198"))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:background "#00736F" :foreground "#69CABF"))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 89)) (:background "#69CABF" :foreground "#00736F"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :underline t))))
 '(company-echo ((((class color) (min-colors 89)) nil)))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#073642" :foreground "#2aa198"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#839496"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#073642"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#073642"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight bold))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#69CABF" :foreground "#00736F"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(company-tooltip-search-selection ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#6c71c4" :weight normal))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#073642" :foreground "#93a1a1" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#073642" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#586e75" :foreground "#93a1a1" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:inherit underline))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:inherit custom-button-unraised :foreground "#d33682"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(diff-refine-added ((((background light) (class color) (min-colors 89)) (:background "#c35ce1469b4d")) (((background dark) (class color) (min-colors 89)) (:background "#57d775c22fc9"))))
 '(diff-refine-changed ((((background light) (class color) (min-colors 89)) (:background "#a6bfc52af271")) (((background dark) (class color) (min-colors 89)) (:background "#3b3a59a686ec"))))
 '(diff-refine-removed ((((background light) (class color) (min-colors 89)) (:background "#f574aa5ca975")) (((background dark) (class color) (min-colors 89)) (:background "#89ef3ed83df0"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#002b36"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :weight bold))))
 '(epa-mark ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(epa-string ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:inverse-video t :slant italic))))
 '(epa-validity-high ((((class color) (min-colors 89)) (:weight bold))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:slant italic))))
 '(epa-validity-medium ((((class color) (min-colors 89)) (:slant italic))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#268bd2") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#69B7F0" :background "#00629D" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#69B7F0" :background "#00629D" :weight bold))))
 '(flymake-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#FF6E64" :background "#990A1B" :weight bold :underline t))))
 '(flymake-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#DEB542" :background "#7B6000" :weight bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#b58900" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:inherit match))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#073642"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#002b36" :background "#b58900" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 89)) (:background "#dc322f" :foreground "#002b36" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(iedit-occurrence ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#d33682" :bold t))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic :weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:inherit info-node))))
 '(info-header-xref ((((class color) (min-colors 89)) (:inherit info-xref))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit match))))
 '(info-menu-header ((((class color) (min-colors 89)) (:inherit variable-pitch :weight bold))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(info-xref ((((class color) (min-colors 89)) (:inherit link))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:inherit (link-visited info-xref)))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:weight bold :background "#073642" :underline t))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#cb4b16"))))
 '(linum ((((class color) (min-colors 89)) (:weight thin :underline nil :foreground "#586e75" :background "#002b36"))))
 '(line-number ((((class color) (min-colors 89)) (:weight thin :underline nil :foreground "#586e75" :background "#002b36"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#839496" :weight normal))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#839496" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#839496" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(mc/cursor-face ((((class color) (min-colors 89)) (:inherit cursor :inverse-video nil))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#073642" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#002b36")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#839496" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36" :weight normal :box (:line-width 2 :color "#002b36") :inverse-video nil :overline nil :slant normal :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#586e75" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#268bd2" :background "#002b36"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#586e75" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) nil)))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:inherit org-meta-line :underline t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:inherit org-meta-line :overline t))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#839496" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#002b36"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#cb4b16" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.15))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :height 1.1))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(org-macro ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#073642"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#073642" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#073642" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#dc322f" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#d33682" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#dc322f"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#cb4b16" :height 1.3))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900" :height 1.2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.15))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :height 1.1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#002b36"))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#002b36"))))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#586e75"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#93a1a1"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#657b83"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#073642" :foreground "#657b83"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#073642" :foreground "#586e75"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#586e75"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#073642" :background "#dc322f" :weight bold))))
 '(skewer-error-face ((((class color) (min-colors 89)) (:foreground "#cb4b16" :underline nil))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:background unspecified :foreground "#d33682" :weight bold))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground "#073642" :background "#dc322f" :weight bold))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#586e75"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#839496"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#073642"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#268bd2" :foreground "#002b36" :overline "#00736F"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#93a1a1"))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#7B6000" :foreground "#DEB542" :inherit variable-pitch))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#002b36"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#002b36" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) (:inherit secondary-selection))))
 '(default ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36")))))

(provide-theme 'solarized-dark)
